### Dieses Vagrantfile wird für euch so nicht funktionieren und müsst ihr noch entsprechend anpassen (box url, networking, port forwarding)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-precise12042-x64-vbox43"
  config.vm.box_url = "/Volumes/nonsens/20_Ressourcen/vagrant/ubuntu-precise12042-x64-vbox43.box"

  config.vm.network "private_network", ip: "33.33.33.2"

  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.synced_folder "~/fhl_dev/", "/fhl_dev/", 
    id: "vagrant-root",
    :nfs => false, 
    :owner => "vagrant",
    :group => "www-data",
    :mount_options => ["dmode=775","fmode=664"]

  config.vm.usable_port_range = (2222..2222)
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--name", "lamp"]
    virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    virtualbox.customize ["modifyvm", :id, "--memory", "512"]
    virtualbox.customize ["setextradata", :id, "--VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.vm.provision :shell, :path => "provision.sh"

  config.ssh.username = "vagrant"

  config.ssh.shell = "bash -l"

  config.ssh.keep_alive = true
  config.ssh.forward_agent = false
  config.ssh.forward_x11 = false
  config.vagrant.host = :detect
end

