Vagrant.configure("2") do |config|
    config.vm.box = "chef/ubuntu-12.04"

    #config.vm.network :private_network, ip: "192.168.56.110"
    config.ssh.forward_agent = true
    config.vm.network :forwarded_port, host: 4567, guest: 80

    config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 1024]
    end

    config.vm.synced_folder "web", "/var/www/web"

    config.vm.provision :shell, :path => "bootstrap.sh"
end